"
This class contains artifacts to be targeted by the searcher tool during tests.
See `StFinderTest` for users.

"
Class {
	#name : 'StFinderMockA',
	#superclass : 'Object',
	#category : 'NewTools-Finder-Tests',
	#package : 'NewTools-Finder-Tests'
}

{ #category : 'accessing' }
StFinderMockA >> aBCSelectorSearchForRegexpStartWithCase [
	"mock example"
]

{ #category : 'accessing' }
StFinderMockA >> abcSelectorSearchForRegexpStartWithoutCase [
	"mock example"
]

{ #category : 'accessing' }
StFinderMockA >> selectorSearchForExactMatchWithCase1 [
	"mock example"
]

{ #category : 'accessing' }
StFinderMockA >> selectorSearchForExactMatchWithCase2 [
	"mock example"
]

{ #category : 'accessing' }
StFinderMockA >> selectorSearchForExactMatchWithoutCase1 [
	"mock example"
]

{ #category : 'accessing' }
StFinderMockA >> selectorSearchForRegexpWithCaseEndsWithAbc [
	"mock example"
]

{ #category : 'accessing' }
StFinderMockA >> selectorSearchForRegexpWithoutCaseEndsWithabc [
	"mock example"
]

{ #category : 'accessing' }
StFinderMockA >> selectorSearchForSubstringMatch1 [
	"mock example"
]

{ #category : 'accessing' }
StFinderMockA >> selectorSearchForSubstringMatch2 [
	"mock example"
]
