"
This class contains artifacts to be targeted by the searcher tool during tests.
See `StFinderTest` for users.

"
Class {
	#name : 'StFinderMock',
	#superclass : 'Object',
	#category : 'NewTools-Finder-Tests',
	#package : 'NewTools-Finder-Tests'
}

{ #category : 'accessing' }
StFinderMock >> aBCSelectorSearchForRegexpStartWithCase [
]

{ #category : 'accessing' }
StFinderMock >> abcSelectorSearchForRegexpStartWithoutCase [
]

{ #category : 'accessing' }
StFinderMock >> selectorSearchForExactMatchWithCase1 [
]

{ #category : 'accessing' }
StFinderMock >> selectorSearchForExactMatchWithCase2 [
]

{ #category : 'accessing' }
StFinderMock >> selectorSearchForExactMatchWithoutCase1 [
]

{ #category : 'accessing' }
StFinderMock >> selectorSearchForRegexpWithCaseEndsWithAbc [
]

{ #category : 'accessing' }
StFinderMock >> selectorSearchForRegexpWithoutCaseEndsWithAbc [
]

{ #category : 'accessing' }
StFinderMock >> selectorSearchForSubstringMatch1 [
]

{ #category : 'accessing' }
StFinderMock >> selectorSearchForSubstringMatch2 [
]
